# Assignment 2

For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('assets/NISPUF17.csv.')

df.head()

,Unnamed: 0,SEQNUMC,SEQNUMHH,PDAT,PROVWT_D,RDDWT_D,STRATUM,YEAR,AGECPOXR,HAD_CPOX,...,XVRCTY2,XVRCTY3,XVRCTY4,XVRCTY5,XVRCTY6,XVRCTY7,XVRCTY8,XVRCTY9,INS_STAT2_I,INS_BREAK_I
0,1,128521,12852,2,NaN,235.916956,1031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,10741,1074,2,NaN,957.353840,1068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,220011,22001,2,NaN,189.611299,1050,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,86131,8613,1,675.430817,333.447418,1040,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
4,5,227141,22714,1,482.617748,278.768063,1008,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0

EDUC1 – education of the mother

- 1: <12 years 
- 2: 12 years 
- 3: >12 years, not a college graduate 
- 4: College graduate 

-p.51 of the pdf

In [37]:
#Posible values
np.sort(df['EDUC1'].unique())

array([1, 2, 3, 4])

In [40]:
proportions = df['EDUC1'].value_counts(normalize=True)
proportions

EDUC1
4    0.479747
3    0.245881
2    0.172352
1    0.102020
Name: proportion, dtype: float64

In [53]:
proportions.get(1)

np.float64(0.10202002459160373)

In [56]:
def proportion_of_education():
    proportions = df['EDUC1'].value_counts(normalize=True)

    result = {
        "less than high school": proportions.get(1),
        "high school": proportions.get(2),
        "more than high school but not college": proportions.get(3),
        "college": proportions.get(4)
    }
    return result
    raise NotImplementedError()

In [57]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."

## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

CBF_01 – child ever fed breast milk

- 1: Yes 
- 2: No  
- 77: Don’t know 
- 99: Missing 

-p.52 of the pdf

In [59]:
#Posible values
np.sort(df['CBF_01'].unique())

array([ 1,  2, 77, 99])

P_NUMFLU – total number of seasonal influenza doses

In [60]:
#Posible values
np.sort(df['P_NUMFLU'].unique())

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6., nan])

In [65]:
#breastmilk_yes mask
df['CBF_01'] == 1

0         True
1        False
2        False
3        False
4         True
         ...
28460    False
28461     True
28462     True
28463    False
28464     True
Name: CBF_01, Length: 28465, dtype: bool

In [68]:
#df with the breastmilk_yes mask
df[df['CBF_01'] == 1]

,Unnamed: 0,SEQNUMC,SEQNUMHH,PDAT,PROVWT_D,RDDWT_D,STRATUM,YEAR,AGECPOXR,HAD_CPOX,...,XVRCTY2,XVRCTY3,XVRCTY4,XVRCTY5,XVRCTY6,XVRCTY7,XVRCTY8,XVRCTY9,INS_STAT2_I,INS_BREAK_I
0,1,128521,12852,2,NaN,235.916956,1031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,227141,22714,1,482.617748,278.768063,1008,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0
6,7,221381,22138,1,516.427723,248.916038,1008,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
7,8,182861,18286,1,313.225832,163.213401,1001,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
8,9,161121,16112,1,978.042448,718.616990,1016,2017,3.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28458,28459,120601,12060,2,NaN,288.269672,2011,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28459,28460,270341,27034,2,NaN,352.329599,2011,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28461,28462,121401,12140,2,NaN,26.503010,2004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28462,28463,128831,12883,2,NaN,27.520652,2004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28464,28465,244621,24462,2,NaN,27.520652,2004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
#df with the breastmilk_yes mask with just the 'P_NUMFLU' column
df[df['CBF_01'] == 1]['P_NUMFLU']

0        NaN
4        0.0
6        0.0
7        0.0
8        0.0
        ...
28458    NaN
28459    NaN
28461    NaN
28462    NaN
28464    NaN
Name: P_NUMFLU, Length: 24261, dtype: float64

In [70]:
#Mean of the 'P_NUMFLU' column with the breastmilk_yes mask
df[df['CBF_01'] == 1]['P_NUMFLU'].mean()

np.float64(1.8799187420058687)

In [71]:
def average_influenza_doses():
    breastmilk_yes = df[df['CBF_01'] == 1]['P_NUMFLU'].mean()
    breastmilk_no = df[df['CBF_01'] == 2]['P_NUMFLU'].mean()

    return (breastmilk_yes, breastmilk_no)
    raise NotImplementedError()

In [72]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."

## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

HAD_CPOX – did child ever have chicken pox (introduced in 2005; I_HADCPX used through 2004)
- 1: Yes 
- 2: No  
- 77: Don’t know 
- 99: Refused/Missing 

-p.52 of the pdf

In [78]:
#Posible values
np.sort(df['HAD_CPOX'].unique())

array([ 1,  2, 77, 99])

SEX – sex of child 
- 1: Male 
- 2: Female

-p.51 of the pdf

In [79]:
#Posible values
np.sort(df['SEX'].unique())

array([1, 2])

P_NUMVRC – total number of varicella doses

In [81]:
#Posible values
np.sort(df['P_NUMVRC'].unique())

array([ 0.,  1.,  2.,  3., nan])

In [91]:
vaccinated_male = df[
            (df["SEX"] == 1) &
            (df["P_NUMVRC"] >= 1)
        ]
vaccinated_male

,Unnamed: 0,SEQNUMC,SEQNUMHH,PDAT,PROVWT_D,RDDWT_D,STRATUM,YEAR,AGECPOXR,HAD_CPOX,...,XVRCTY2,XVRCTY3,XVRCTY4,XVRCTY5,XVRCTY6,XVRCTY7,XVRCTY8,XVRCTY9,INS_STAT2_I,INS_BREAK_I
10,11,128211,12821,1,335.398714,198.123294,1057,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
12,13,137041,13704,1,82.582116,45.544717,1051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
16,17,188611,18861,1,345.352030,196.111859,1057,2017,NaN,2,...,VO,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
19,20,136171,13617,1,223.451930,136.912758,1059,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
21,22,238751,23875,1,270.449794,134.563612,1058,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28435,28436,250151,25015,1,99.480351,57.116375,2068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28436,28437,79531,7953,1,96.617497,54.463171,2065,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
28438,28439,126141,12614,1,216.225073,126.221620,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
28447,28448,136841,13684,1,593.426753,337.255316,2031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28449,28450,132081,13208,1,166.681363,96.330007,2059,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0

In [90]:
(vaccinated_male["HAD_CPOX"] == 1).sum()

np.int64(68)

In [92]:
def chickenpox_by_sex():
    # Create an empty dictionary to store the results for each sex
    result = {}

    # Iterate over both sexes:
    # SEX = 1 corresponds to males and SEX = 2 corresponds to females
    for sex, name in [(1, "male"), (2, "female")]:

        # Filter the DataFrame to select only:
        # 1. Children of the current sex
        # 2. Children who received at least one dose of the varicella vaccine
        vaccinated = df[
            (df["SEX"] == sex) &
            (df["P_NUMVRC"] >= 1)
        ]

        # Count vaccinated children who contracted chickenpox
        # HAD_CPOX = 1 means the child had chickenpox
        had_chickenpox = (vaccinated["HAD_CPOX"] == 1).sum()

        # Count vaccinated children who did not contract chickenpox
        # HAD_CPOX = 2 means the child did not have chickenpox
        no_chickenpox = (vaccinated["HAD_CPOX"] == 2).sum()

        # Calculate the ratio of vaccinated children who had chickenpox
        # to vaccinated children who did not have chickenpox
        # Store the result under the "male" or "female" key
        result[name] = had_chickenpox / no_chickenpox

    # Return the dictionary containing the results for both sexes
    return result

    raise NotImplementedError()

In [94]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."

In [95]:
chickenpox_by_sex()

{'male': np.float64(0.009675583380762664),
 'female': np.float64(0.0077918259335489565)}

## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

HAD_CPOX – did child ever have chicken pox (introduced in 2005; I_HADCPX used through 2004)
- 1: Yes 
- 2: No  
- 77: Don’t know 
- 99: Refused/Missing 

-p.52 of the pdf

In [97]:
#Posible values
np.sort(df['HAD_CPOX'].unique())

array([ 1,  2, 77, 99])

P_NUMVRC – total number of varicella doses

In [96]:
#Posible values
np.sort(df['P_NUMVRC'].unique())

array([ 0.,  1.,  2.,  3., nan])

In [7]:
New_df = df[["HAD_CPOX", "P_NUMVRC"]].copy()

In [8]:
New_df["HAD_CPOX"].isin([1, 2])

0        True
1        True
2        True
3        True
4        True
         ...
28460    True
28461    True
28462    True
28463    True
28464    True
Name: HAD_CPOX, Length: 28465, dtype: bool

In [21]:
New_df[
        New_df["HAD_CPOX"].isin([1, 2]) &
        New_df["P_NUMVRC"].isin([0, 1, 2, 3])
    ]

       HAD_CPOX  P_NUMVRC
3             2       1.0
4             2       0.0
6             2       1.0
7             2       0.0
8             1       0.0
...         ...       ...
28446         2       1.0
28447         2       1.0
28449         2       1.0
28452         2       1.0
28454         2       1.0

[15286 rows x 2 columns]

In [9]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # Select the two columns needed for the correlation
    New_df = df[["HAD_CPOX", "P_NUMVRC"]].copy()

    # Keep only valid responses and remove missing values
    New_df = New_df[
        New_df["HAD_CPOX"].isin([1, 2]) &
        New_df["P_NUMVRC"].isin([0, 1, 2, 3])
    ].dropna()

    # Calculate the Pearson correlation coefficient
    corr, pval = stats.pearsonr(
        New_df["HAD_CPOX"],
        New_df["P_NUMVRC"]
    )

    return float(corr)
    
    raise NotImplementedError()

In [10]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."